# Environment
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=all

# Project Identity
group=io.hoyatla.animatruc
version=1.0.0-proprietary.0
mod_id=animatruc
mod_display_name=AnimaTruc
mod_authors=Hoyatla
mod_license=All Rights Reserved
mod_description=Proprietary animation runtime for Minecraft mods with adaptive scheduling and deterministic blending.

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.4.8
forge_loader_range=[47,)
forge_version_range=[47.1,)
parchment_version=2023.09.03
