modLoader="javafml"
loaderVersion="${forge_loader_range}"
license="${compat_license}"

[[mods]]
modId="${compat_mod_id}"
version="${version}"
displayName="${compat_display_name}"
logoFile="compat-animatruc-geckolib-icon-400.png"
credits="${compat_authors}"
authors="${compat_authors}"
description='''
${compat_description}
'''

[[dependencies.${compat_mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${compat_mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${compat_mod_id}]]
modId="animatruc"
mandatory=true
versionRange="${animatruc_required_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${compat_mod_id}]]
modId="geckolib"
mandatory=true
versionRange="${geckolib_required_range}"
ordering="AFTER"
side="BOTH"
