package io.hoyatla.animatruc.core.importer.animatruc;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonParser;
import io.hoyatla.animatruc.core.animation.AnimationChannel;
import io.hoyatla.animatruc.core.animation.AnimationClip;
import io.hoyatla.animatruc.core.animation.BoneAnimationTrack;
import io.hoyatla.animatruc.core.animation.InterpolationMode;
import io.hoyatla.animatruc.core.animation.Interpolators;
import io.hoyatla.animatruc.core.animation.Keyframe;
import io.hoyatla.animatruc.core.animation.Transform;
import io.hoyatla.animatruc.core.asset.AnimationAssetPack;
import io.hoyatla.animatruc.core.asset.ModelMeshSkin;
import io.hoyatla.animatruc.core.asset.ModelBone;
import io.hoyatla.animatruc.core.asset.ModelCube;
import io.hoyatla.animatruc.core.asset.ModelGeometry;
import io.hoyatla.animatruc.core.asset.PackMaterial;
import io.hoyatla.animatruc.core.asset.PackMetadata;
import io.hoyatla.animatruc.core.asset.PackTexture;
import io.hoyatla.animatruc.core.asset.ModelMesh;
import io.hoyatla.animatruc.core.asset.ModelMeshFace;
import io.hoyatla.animatruc.core.asset.ModelSkeleton;
import io.hoyatla.animatruc.core.asset.ModelUv;
import io.hoyatla.animatruc.core.asset.VertexInfluence;
import io.hoyatla.animatruc.core.importer.AnimationAssetImporter;
import io.hoyatla.animatruc.core.importer.ModelImportException;
import io.hoyatla.animatruc.core.importer.ModelImportOptions;
import io.hoyatla.animatruc.core.math.Quatf;
import io.hoyatla.animatruc.core.math.Vec3f;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

/**
 * Imports AnimaTruc pack JSON generated by authoring tools such as the Blockbench plugin.
 */
public final class AnimaTrucJsonImporter implements AnimationAssetImporter {
    @Override
    public AnimationAssetPack importFromString(String payload, ModelImportOptions options) {
        Objects.requireNonNull(payload, "payload");
        ModelImportOptions safeOptions = options == null ? ModelImportOptions.DEFAULT : options;

        JsonObject root = parseRoot(payload);
        PackMetadata metadata = parseMetadata(root);
        ModelSkeleton skeleton = parseSkeleton(root, safeOptions.translationScale());
        ModelGeometry geometry = parseGeometry(root, safeOptions.translationScale());
        Map<String, AnimationClip> clips = parseClips(root, safeOptions);

        return new AnimationAssetPack(metadata, skeleton, geometry, clips);
    }

    private static JsonObject parseRoot(String payload) {
        try {
            JsonElement element = JsonParser.parseString(payload);

            if (!element.isJsonObject())
                throw new ModelImportException("Invalid AnimaTruc JSON: root must be an object.");

            return element.getAsJsonObject();
        }
        catch (JsonParseException exception) {
            throw new ModelImportException("Invalid AnimaTruc JSON payload.", exception);
        }
    }

    private static ModelSkeleton parseSkeleton(JsonObject root, float translationScale) {
        JsonObject skeletonObject = getObject(root, "skeleton");

        if (skeletonObject == null)
            throw new ModelImportException("Missing 'skeleton' section in AnimaTruc pack.");

        JsonArray bonesArray = getArray(skeletonObject, "bones");

        if (bonesArray == null)
            throw new ModelImportException("Missing 'skeleton.bones' section in AnimaTruc pack.");

        List<ModelBone> bones = new ArrayList<>(bonesArray.size());

        for (JsonElement boneElement : bonesArray) {
            JsonObject boneObject = asObject(boneElement);

            if (boneObject == null)
                continue;

            String name = getString(boneObject, "name", null);

            if (name == null || name.isBlank())
                continue;

            String parent = getString(boneObject, "parent", null);
            Vec3f pivot = parseVec3(boneObject.get("pivot"), Vec3f.ZERO, translationScale);
            Transform bindPose = parseBindPose(getObject(boneObject, "bindPose"), translationScale);

            bones.add(new ModelBone(name, parent, pivot, bindPose));
        }

        return new ModelSkeleton(bones);
    }

    private static PackMetadata parseMetadata(JsonObject root) {
        JsonObject metadataObject = getObject(root, "meta");

        if (metadataObject == null)
            return PackMetadata.EMPTY;

        List<PackTexture> textures = parseTextures(getArray(metadataObject, "textures"));
        List<PackMaterial> materials = parseMaterials(getArray(metadataObject, "materials"));

        return new PackMetadata(
                getString(metadataObject, "source", null),
                getString(metadataObject, "pluginId", null),
                getString(metadataObject, "projectName", null),
                getString(metadataObject, "exportedAt", null),
                textures,
                materials
        );
    }

    private static Transform parseBindPose(JsonObject bindPoseObject, float translationScale) {
        if (bindPoseObject == null)
            return Transform.IDENTITY;

        Vec3f translation = parseVec3(bindPoseObject.get("translation"), Vec3f.ZERO, translationScale);
        Vec3f scale = parseVec3(bindPoseObject.get("scale"), Vec3f.ONE, 1f);
        Quatf rotation = parseRotation(bindPoseObject.get("rotation"));

        return new Transform(translation, rotation, scale);
    }

    private static Quatf parseRotation(JsonElement rotationElement) {
        if (rotationElement == null || rotationElement.isJsonNull())
            return Quatf.IDENTITY;

        if (rotationElement.isJsonArray()) {
            JsonArray array = rotationElement.getAsJsonArray();

            if (array.size() >= 4) {
                return new Quatf(
                        parseFloat(array.get(0), 0f),
                        parseFloat(array.get(1), 0f),
                        parseFloat(array.get(2), 0f),
                        parseFloat(array.get(3), 1f)
                ).normalize();
            }

            if (array.size() >= 3) {
                return Quatf.fromEulerDegrees(
                        parseFloat(array.get(0), 0f),
                        parseFloat(array.get(1), 0f),
                        parseFloat(array.get(2), 0f)
                );
            }
        }

        JsonObject rotationObject = asObject(rotationElement);

        if (rotationObject != null) {
            if (rotationObject.has("w")) {
                return new Quatf(
                        parseFloat(rotationObject.get("x"), 0f),
                        parseFloat(rotationObject.get("y"), 0f),
                        parseFloat(rotationObject.get("z"), 0f),
                        parseFloat(rotationObject.get("w"), 1f)
                ).normalize();
            }

            return Quatf.fromEulerDegrees(
                    parseFloat(rotationObject.get("x"), 0f),
                    parseFloat(rotationObject.get("y"), 0f),
                    parseFloat(rotationObject.get("z"), 0f)
            );
        }

        return Quatf.IDENTITY;
    }

    private static Map<String, AnimationClip> parseClips(JsonObject root, ModelImportOptions options) {
        Map<String, AnimationClip> clipsByName = new LinkedHashMap<>();
        JsonArray clipsArray = getArray(root, "clips");

        if (clipsArray == null)
            return clipsByName;

        for (int clipIndex = 0; clipIndex < clipsArray.size(); clipIndex++) {
            JsonObject clipObject = asObject(clipsArray.get(clipIndex));

            if (clipObject == null)
                continue;

            String name = getString(clipObject, "name", "clip_" + clipIndex);
            boolean looping = getBoolean(clipObject, "looping", options.defaultLooping());
            float lengthTicks = parseClipLengthTicks(clipObject, options);
            JsonObject tracksObject = getObject(clipObject, "tracks");
            Map<String, BoneAnimationTrack> tracks = new LinkedHashMap<>();
            float inferredLengthTicks = 0f;

            if (tracksObject != null) {
                for (Map.Entry<String, JsonElement> trackEntry : tracksObject.entrySet()) {
                    JsonObject trackObject = asObject(trackEntry.getValue());

                    if (trackObject == null)
                        continue;

                    TrackBuilder builder = new TrackBuilder();
                    parseVectorTrack(
                            getArray(trackObject, "translation"),
                            builder.translation,
                            builder::noteTick,
                            options.translationScale(),
                            Vec3f.ZERO
                    );
                    parseRotationTrack(getArray(trackObject, "rotation"), builder.rotation, builder::noteTick);
                    parseVectorTrack(
                            getArray(trackObject, "scale"),
                            builder.scale,
                            builder::noteTick,
                            1f,
                            Vec3f.ONE
                    );

                    inferredLengthTicks = Math.max(inferredLengthTicks, builder.maxTick);
                    tracks.put(trackEntry.getKey(), builder.build());
                }
            }

            clipsByName.put(name, new AnimationClip(name, Math.max(lengthTicks, inferredLengthTicks), looping, tracks));
        }

        return clipsByName;
    }

    private static ModelGeometry parseGeometry(JsonObject root, float translationScale) {
        JsonObject modelObject = getObject(root, "model");

        if (modelObject == null)
            return ModelGeometry.EMPTY;

        JsonArray cubesArray = getArray(modelObject, "cubes");
        JsonArray meshesArray = getArray(modelObject, "meshes");
        List<ModelCube> cubes = new ArrayList<>(cubesArray == null ? 0 : cubesArray.size());
        List<ModelMesh> meshes = new ArrayList<>(meshesArray == null ? 0 : meshesArray.size());

        if (cubesArray != null) {
            for (JsonElement cubeElement : cubesArray) {
                JsonObject cubeObject = asObject(cubeElement);

                if (cubeObject == null)
                    continue;

                String boneName = getString(cubeObject, "bone", null);

                if (boneName == null || boneName.isBlank())
                    continue;

                String name = getString(cubeObject, "name", boneName + "_cube");
                String material = getString(cubeObject, "material", null);
                Vec3f from = parseVec3(cubeObject.get("from"), Vec3f.ZERO, translationScale);
                Vec3f to = parseVec3(cubeObject.get("to"), Vec3f.ZERO, translationScale);
                float inflate = getFloat(cubeObject, "inflate", 0f) * translationScale;
                boolean mirror = getBoolean(cubeObject, "mirror", false);

                cubes.add(new ModelCube(name, boneName, material, from, to, inflate, mirror));
            }
        }

        if (meshesArray != null) {
            for (JsonElement meshElement : meshesArray) {
                JsonObject meshObject = asObject(meshElement);

                if (meshObject == null)
                    continue;

                String boneName = getString(meshObject, "bone", null);

                if (boneName == null || boneName.isBlank())
                    continue;

                String name = getString(meshObject, "name", boneName + "_mesh");
                String material = getString(meshObject, "material", null);
                Vec3f origin = parseVec3(meshObject.get("origin"), Vec3f.ZERO, translationScale);
                List<Vec3f> vertices = parseVertices(getArray(meshObject, "vertices"), translationScale);
                List<ModelMeshFace> faces = parseFaces(getArray(meshObject, "faces"));
                ModelMeshSkin skin = parseSkin(getObject(meshObject, "skin"));

                if (!vertices.isEmpty() && !faces.isEmpty())
                    meshes.add(new ModelMesh(name, boneName, material, origin, vertices, faces, skin));
            }
        }

        if (cubes.isEmpty() && meshes.isEmpty())
            return ModelGeometry.EMPTY;

        return new ModelGeometry(cubes, meshes);
    }

    private static List<Vec3f> parseVertices(JsonArray verticesArray, float translationScale) {
        if (verticesArray == null)
            return List.of();

        List<Vec3f> vertices = new ArrayList<>(verticesArray.size());

        for (JsonElement vertexElement : verticesArray) {
            vertices.add(parseVec3(vertexElement, Vec3f.ZERO, translationScale));
        }

        return vertices;
    }

    private static List<ModelMeshFace> parseFaces(JsonArray facesArray) {
        if (facesArray == null)
            return List.of();

        List<ModelMeshFace> faces = new ArrayList<>(facesArray.size());

        for (JsonElement faceElement : facesArray) {
            JsonObject faceObject = asObject(faceElement);

            if (faceObject == null)
                continue;

            List<Integer> indices = parseFaceIndices(getArray(faceObject, "indices"));

            if (indices.size() < 3)
                continue;

            List<ModelUv> uvs = parseFaceUvs(getArray(faceObject, "uvs"));
            faces.add(new ModelMeshFace(indices, uvs));
        }

        return faces;
    }

    private static ModelMeshSkin parseSkin(JsonObject skinObject) {
        if (skinObject == null)
            return null;

        JsonArray influencesArray = getArray(skinObject, "influences");

        if (influencesArray == null || influencesArray.isEmpty())
            return null;

        List<List<VertexInfluence>> influencesByVertex = new ArrayList<>(influencesArray.size());

        for (JsonElement vertexElement : influencesArray) {
            JsonArray vertexArray = vertexElement != null && vertexElement.isJsonArray() ? vertexElement.getAsJsonArray() : null;
            List<VertexInfluence> influences = new ArrayList<>();

            if (vertexArray != null) {
                for (JsonElement influenceElement : vertexArray) {
                    JsonObject influenceObject = asObject(influenceElement);

                    if (influenceObject == null)
                        continue;

                    String boneName = getString(influenceObject, "bone", null);

                    if (boneName == null || boneName.isBlank())
                        continue;

                    float weight = getFloat(influenceObject, "weight", 0f);

                    if (weight > 0f)
                        influences.add(new VertexInfluence(boneName, weight));
                }
            }

            influencesByVertex.add(influences);
        }

        return new ModelMeshSkin(getBoolean(skinObject, "modelSpaceVertices", true), influencesByVertex);
    }

    private static List<PackTexture> parseTextures(JsonArray texturesArray) {
        if (texturesArray == null)
            return List.of();

        List<PackTexture> textures = new ArrayList<>(texturesArray.size());

        for (JsonElement textureElement : texturesArray) {
            JsonObject textureObject = asObject(textureElement);

            if (textureObject == null)
                continue;

            String name = getString(textureObject, "name", null);

            if (name == null || name.isBlank())
                continue;

            textures.add(new PackTexture(
                    name,
                    getString(textureObject, "path", null),
                    (int)getFloat(textureObject, "width", 0f),
                    (int)getFloat(textureObject, "height", 0f)
            ));
        }

        return textures;
    }

    private static List<PackMaterial> parseMaterials(JsonArray materialsArray) {
        if (materialsArray == null)
            return List.of();

        List<PackMaterial> materials = new ArrayList<>(materialsArray.size());

        for (JsonElement materialElement : materialsArray) {
            JsonObject materialObject = asObject(materialElement);

            if (materialObject == null)
                continue;

            String name = getString(materialObject, "name", null);

            if (name == null || name.isBlank())
                continue;

            materials.add(new PackMaterial(
                    name,
                    getString(materialObject, "texture", null),
                    getString(materialObject, "renderType", null)
            ));
        }

        return materials;
    }

    private static List<Integer> parseFaceIndices(JsonArray indicesArray) {
        if (indicesArray == null)
            return List.of();

        List<Integer> indices = new ArrayList<>(indicesArray.size());

        for (JsonElement indexElement : indicesArray) {
            try {
                indices.add(indexElement.getAsInt());
            }
            catch (RuntimeException ignored) {
                // Skip malformed index entries.
            }
        }

        return indices;
    }

    private static List<ModelUv> parseFaceUvs(JsonArray uvsArray) {
        if (uvsArray == null)
            return List.of();

        List<ModelUv> uvs = new ArrayList<>(uvsArray.size());

        for (JsonElement uvElement : uvsArray) {
            if (uvElement == null || uvElement.isJsonNull())
                continue;

            if (uvElement.isJsonArray()) {
                JsonArray uvArray = uvElement.getAsJsonArray();

                if (uvArray.size() >= 2) {
                    uvs.add(new ModelUv(
                            parseFloat(uvArray.get(0), 0f),
                            parseFloat(uvArray.get(1), 0f)
                    ));
                }
                continue;
            }

            JsonObject uvObject = asObject(uvElement);

            if (uvObject != null) {
                uvs.add(new ModelUv(
                        parseFloat(uvObject.get("u"), 0f),
                        parseFloat(uvObject.get("v"), 0f)
                ));
            }
        }

        return uvs;
    }

    private static float parseClipLengthTicks(JsonObject clipObject, ModelImportOptions options) {
        float lengthTicks = getFloat(clipObject, "lengthTicks", -1f);

        if (lengthTicks >= 0f)
            return lengthTicks;

        float lengthSeconds = getFloat(clipObject, "lengthSeconds", 0f);

        return Math.max(0f, lengthSeconds * options.ticksPerSecond());
    }

    private static void parseVectorTrack(
            JsonArray keyframes,
            List<Keyframe<Vec3f>> destination,
            TickConsumer tickConsumer,
            float scaleMultiplier,
            Vec3f fallbackValue) {
        if (keyframes == null)
            return;

        for (JsonElement keyframeElement : keyframes) {
            JsonObject keyframeObject = asObject(keyframeElement);

            if (keyframeObject == null)
                continue;

            float tick = getFloat(keyframeObject, "tick", getFloat(keyframeObject, "time", 0f));
            InterpolationMode interpolation = parseInterpolation(getString(keyframeObject, "interpolation", "linear"));
            Vec3f value = parseVec3(keyframeObject.get("value"), fallbackValue, scaleMultiplier);
            tickConsumer.accept(tick);
            destination.add(new Keyframe<>(tick, value, interpolation));
        }
    }

    private static void parseRotationTrack(
            JsonArray keyframes,
            List<Keyframe<Quatf>> destination,
            TickConsumer tickConsumer) {
        if (keyframes == null)
            return;

        for (JsonElement keyframeElement : keyframes) {
            JsonObject keyframeObject = asObject(keyframeElement);

            if (keyframeObject == null)
                continue;

            float tick = getFloat(keyframeObject, "tick", getFloat(keyframeObject, "time", 0f));
            InterpolationMode interpolation = parseInterpolation(getString(keyframeObject, "interpolation", "linear"));
            Quatf value = parseRotation(keyframeObject.get("value"));
            tickConsumer.accept(tick);
            destination.add(new Keyframe<>(tick, value, interpolation));
        }
    }

    private static InterpolationMode parseInterpolation(String value) {
        String normalized = value == null ? "" : value.trim().toUpperCase(Locale.ROOT);
        return "STEP".equals(normalized) ? InterpolationMode.STEP : InterpolationMode.LINEAR;
    }

    private static Vec3f parseVec3(JsonElement element, Vec3f fallback, float multiplier) {
        if (element == null || element.isJsonNull())
            return fallback;

        if (element.isJsonArray()) {
            JsonArray array = element.getAsJsonArray();

            if (array.size() < 3)
                return fallback;

            return new Vec3f(
                    parseFloat(array.get(0), fallback.x()) * multiplier,
                    parseFloat(array.get(1), fallback.y()) * multiplier,
                    parseFloat(array.get(2), fallback.z()) * multiplier
            );
        }

        JsonObject object = asObject(element);

        if (object == null)
            return fallback;

        return new Vec3f(
                parseFloat(object.get("x"), fallback.x()) * multiplier,
                parseFloat(object.get("y"), fallback.y()) * multiplier,
                parseFloat(object.get("z"), fallback.z()) * multiplier
        );
    }

    private static JsonObject asObject(JsonElement element) {
        return element != null && element.isJsonObject() ? element.getAsJsonObject() : null;
    }

    private static JsonObject getObject(JsonObject object, String fieldName) {
        return asObject(object.get(fieldName));
    }

    private static JsonArray getArray(JsonObject object, String fieldName) {
        JsonElement element = object.get(fieldName);
        return element != null && element.isJsonArray() ? element.getAsJsonArray() : null;
    }

    private static String getString(JsonObject object, String fieldName, String fallback) {
        JsonElement element = object.get(fieldName);

        if (element == null || element.isJsonNull())
            return fallback;

        try {
            return element.getAsString();
        }
        catch (RuntimeException ignored) {
            return fallback;
        }
    }

    private static boolean getBoolean(JsonObject object, String fieldName, boolean fallback) {
        JsonElement element = object.get(fieldName);

        if (element == null || element.isJsonNull())
            return fallback;

        try {
            return element.getAsBoolean();
        }
        catch (RuntimeException ignored) {
            return fallback;
        }
    }

    private static float getFloat(JsonObject object, String fieldName, float fallback) {
        return parseFloat(object.get(fieldName), fallback);
    }

    private static float parseFloat(JsonElement element, float fallback) {
        if (element == null || element.isJsonNull())
            return fallback;

        try {
            return element.getAsFloat();
        }
        catch (RuntimeException ignored) {
            return fallback;
        }
    }

    @FunctionalInterface
    private interface TickConsumer {
        void accept(float tick);
    }

    private static final class TrackBuilder {
        private final List<Keyframe<Vec3f>> translation = new ArrayList<>();
        private final List<Keyframe<Quatf>> rotation = new ArrayList<>();
        private final List<Keyframe<Vec3f>> scale = new ArrayList<>();
        private float maxTick;

        private void noteTick(float tick) {
            this.maxTick = Math.max(this.maxTick, tick);
        }

        private BoneAnimationTrack build() {
            return new BoneAnimationTrack(
                    new AnimationChannel<>(this.translation, Interpolators.VEC3, Vec3f.ZERO),
                    new AnimationChannel<>(this.rotation, Interpolators.QUAT, Quatf.IDENTITY),
                    new AnimationChannel<>(this.scale, Interpolators.VEC3, Vec3f.ONE)
            );
        }
    }
}
